# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe4f4f21c0c86ac9b85780bece798fa5ab9ba7cc3dd3c8e83df0c41a97e5686e67b3cacd506b4358cae3ac53d85ab54e1ca5e4fd26a88d61a86bd995e4abdb9

test:
  secret_key_base: f453d93f482fe768a6d17c054f615fe24ea75ba43ccd38c0feb5577968c2df806713b096d93818e610d7634a730ad0d4e65808d4840093418486a5c224240d7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
